### ISSUE TITLE
build time environment variables 

### ISSUE THREAD

**Issue by deliriousrhino** [robinvdvleuten/preact-cli-plugin-env-vars#1]
Hi thanks for the repo, when building with the CLI what is the process to pass build time environment variables

**Comment by robinvdvleuten** [comment]
It works in a similar fashion as with the CRA, read more about it here => https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables

**Comment by deliriousrhino** [comment]
Its does not seem to pick up .env.production variables on build.
but I was able to set the variables in my package script when building the bundles for product
Thanks

**Comment by orangecoloured** [comment]
I'm setting `PREACT_APP_VERSION=$npm_package_version` in the `.env` file, but I get `PREACT_APP_VERSION: "$npm_package_version"` in the app.
